In [1]:
import numpy as np

5 basic numerical types:
    bool
    int
    unsigned int
    floating point
    complex

In [2]:
x = np.float32(1.0)

In [3]:
x

1.0

In [4]:
y = np.int_([1,2,4])

In [5]:
y

array([1, 2, 4])

In [7]:
z = np.arange(3, dtype=np.int8)
z

array([0, 1, 2], dtype=int8)

In [12]:
z1 = np.arange(3)
z1

array([0, 1, 2])

In [13]:
type(z1)

numpy.ndarray

In [14]:
type(z1[0])

numpy.int32

In [15]:
z1.dtype

dtype('int32')

## Overflow Errors

In [16]:
np.power(100, 8, dtype=np.int64)

10000000000000000

In [18]:
np.power(100, 8, dtype=np.int32)

1874919424

## Quickstart

In [20]:
ar = [[1., 0., 0.],
     [0., 1., 2.]]

In [21]:
a = np.arange(15).reshape(3, 5)

In [22]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
a.shape

(3, 5)

In [25]:
a.ndim


2

In [26]:
a.dtype

dtype('int32')

In [27]:
type(a)

numpy.ndarray

In [28]:
b = np.array([(1,2,3), (4,5,6)])

In [29]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
b.ndim

2

In [31]:
c = np.array([1,2,3])

In [32]:
c.ndim

1

In [37]:
print(np.arange(15).reshape(3,5))

2


## Basic operations

In [39]:
a = np.array([20,30,40,50])
b = np.arange(4)

In [40]:
b

array([0, 1, 2, 3])

In [41]:
a

array([20, 30, 40, 50])

In [42]:
a-b

array([20, 29, 38, 47])

In [43]:
a+b

array([20, 31, 42, 53])

In [44]:
a*b

array([  0,  30,  80, 150])

In [46]:
a - 10

array([10, 20, 30, 40])

In [48]:
A = np.array([[1, 1],
             [0, 1]])

B = np.array([[2, 0],
             [3, 4]])

In [49]:
A + B

array([[3, 1],
       [3, 5]])

In [50]:
A - B

array([[-1,  1],
       [-3, -3]])

In [51]:
A * B

array([[2, 0],
       [0, 4]])

In [52]:
A @ B

array([[5, 4],
       [3, 4]])

In [53]:
A.dot(B)

array([[5, 4],
       [3, 4]])

## Indexing, Slicing & Iterating

In [58]:
a = np.arange(10)**2

In [59]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [60]:
a[0:6:2] = 888

In [61]:
a

array([888,   1, 888,   9, 888,  25,  36,  49,  64,  81], dtype=int32)

In [62]:
for i in a:
    print(i**(1/2))

29.79932885150268
1.0
29.79932885150268
3.0
29.79932885150268
5.0
6.0
7.0
8.0
9.0


In [74]:
def f(x,y):
    return 10*x+y

In [75]:
e = np.fromfunction(f,(5,4), dtype=int)

In [76]:
e

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [77]:
e[2,3]

23

In [104]:
e[-1,0:3]

array([40, 41, 42])

In [105]:
e

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [108]:
for row in e:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [111]:
e.T.T

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])